### PR TITLE
Feature: pinch vertical gesture

### LINKED ISSUE #130: Add PinchGestureHandler
It would be great to have an option to set PinchGestureHandler. For example we could set the amount of day(s) displayed using this event handler.

### PR DESCRIPTION
**Pull request by pdpino**
Fixes #130  (see demo in https://github.com/hoangnm/react-native-week-view/issues/130#issuecomment-1546529513)

### CODE REVIEW

**Comment by pdpino** [comment]
@hoangnm have u been able to check this PR?

**Review by hoangnm — APPROVED** [review]
Looking good!

**Comment by rdewolff** [comment]
This doesn't work for me, neither on the web, neither on mobile. It crashes with the following error. Here is the context and the error:

```
      <WeekView
        events={myEvents}
        selectedDate={new Date(2023, 1, 20, 12)}
        numberOfDays={7}
        pageStartAt={{ weekday: 1 }}
      />
```

Error:
```
VerticalDimContext.js:29 Uncaught TypeError: Cannot read properties of undefined (reading 'Pinch')
    at useSetupDimensions (VerticalDimContext.js:29:40)
    at VerticalDimensionsProvider (VerticalDimContext.js:68:17)
    at renderWithHooks (react-dom.development.js:14803:1)
    at mountIndeterminateComponent (react-dom.development.js:17482:1)
    at beginWork (react-dom.development.js:18596:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237:1)
    at invokeGuardedCallback (react-dom.development.js:292:1)
    at beginWork$1 (react-dom.development.js:23203:1)
    at performUnitOfWork (react-dom.development.js:22157:1)
useSetupDimensions @ VerticalDimContext.js:29
VerticalDimensionsProvider @ VerticalDimContext.js:68
renderWithHooks @ react-dom.development.js:14803
mountIndeterminateComponent @ react-dom.development.js:17482
beginWork @ react-dom.development.js:18596
callCallback @ react-dom.development.js:188
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
beginWork$1 @ react-dom.development.js:23203
performUnitOfWork @ react-dom.development.js:22157
workLoopSync @ react-dom.development.js:22130
performSyncWorkOnRoot @ react-dom.development.js:21756
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
discreteUpdates$1 @ react-dom.development.js:21893
discreteUpdates @ react-dom.development.js:806
dispatchDiscreteEvent @ react-dom.development.js:4168
react-dom.development.js:19527 The above error occurred in the <VerticalDimensionsProvider> component:
    in VerticalDimensionsProvider (at WeekView.js:615)
    in HeaderRefContextProvider (at WeekView.js:571)
    in div (created by View)
    in View (at WeekView.js:570)
    in WeekView (at agenda-screen.tsx:238)
    in div (created by View)
    in View (at screen.web.tsx:31)
    in div (created by View)
    in View (created by KeyboardAvoidingView)
    in KeyboardAvoidingView (at screen.web.tsx:25)
    in ScreenWithoutScrolling (at screen.web.tsx:97)
    in Screen (at screen-themed.tsx:17)
    in ScreenWithTheme (created by Context.Consumer)
    in Wrapper (created by ScreenWithTheme)
    in ScreenWithTheme (at agenda-screen.tsx:230)
    in wrappedComponent (created by SceneView)
    in StaticContainer
    in StaticContainer (created by SceneView)
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by DrawerView)
    in div (created by View)
    in View (created by ResourceSavingScene)
    in ResourceSavingScene (created by DrawerView)
    in div (created by View)
[...]
```

**Comment by rdewolff** [comment]
Deleted my previous messsage, did not see this message:

```
- Breaking change: add [react-native-gesture-handler](https://docs.swmansion.com/react-native-gesture-handler/docs/installation/) v2 and [react-native-reanimated](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation) v2 as peer dependencies. This change helps drag&drop smoother [#175](https://github.com/hoangnm/react-native-week-view/pull/175)
```

All good 😉

**Pull request merged**
