### PR TITLE
Refactor: compute WeekView width dinamically

### PR DESCRIPTION
**Pull request by pdpino**
Main changes:

* Remove hard-coded `CONTAINER_WIDTH` variable
* Calculate dynamically `dimensions = { dayWidth, pageWidth, timeLabelsWidth }` to define the widths of the views

This refactor will allow solving later:

* issues #128, #185, and #186 **(already solved in upcoming PRs)**
* responsiveness (#38, #142) **(in the future)**

### CODE REVIEW

**Comment by hoangnm** [comment]
So this PR is a baseline for later improvements, @pdpino ?

**Comment by pdpino** [comment]
> So is this PR a baseline for the later improvements

Yes @hoangnm

**Comment by hoangnm** [comment]
Thank @pdpino , it looks promising!

**Comment by rdewolff** [comment]
I have noticed the component is not displayed properly on a browser when using `react-native-web`. Have you checked it?

**Comment by pdpino** [comment]
@rdewolff We haven't checked in react-native-web.

Could you open a different issue with this, and show a screenshot or video with the error?

**Comment by rdewolff** [comment]
Will do!

**Pull request merged**
