### PR TITLE
Chore: github-actions (linter and tests)

### PR DESCRIPTION
**Pull request by pdpino**
* Create github actions to run linter and tests on every PR (run on main folder and `example/` folder)
* Add simple test in the main folder (will add more later)

I'm not sure why the actions are not running for this PR. @hoangnm maybe you have to approve them? [see here](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks). We should be seeing something like:

image

### CODE REVIEW

**Comment by pdpino** [comment]
@hoangnm I suggest reviewing this PR before the other ones, so the other ones get tested with github actions :rocket:

**Comment by pdpino** [comment]
Hi @hoangnm, have you had time to check this PR? :slightly_smiling_face:

**Comment by hoangnm** [comment]
This would be nice, we have to find a way to support writing tests again.

**Comment by pdpino** [comment]
Closing, adding tests in #195

**Pull request closed without merging**
