### PR TITLE
Feature: fixed-week behavior

### LINKED ISSUE #74: Is it possible to disable swiping?
I'm trying to make a weekly school schedule where I want the Mon-Fri events to be the same. Is there any way to disable swiping? If not, is there an easy way to repeat the events?
*Edit: By swiping i am referring to horizontal swiping. The vertical scroll is fine for me.

### PR DESCRIPTION
**Pull request by pdpino**
Fixes #74.

I created a `FixedWeekView` component, to be used as a fixed timetable showing one week.

Some code is repeated from `WeekView`, which is not ideal (though I moved most functions to `utils.js`). I created it this way for two main reasons: 
1. If the `WeekView` component were to be reused, there would be useless virtualized-lists within the component, which is not optimal
2. In the future both components may differ more, and may be useful to have them separated.

If we wanted to avoid code repetition with a new component, instead of creating `FixedWeekView` as a component of its own, we could add a prop to `WeekView` such as `fixedHorizontally={true/false}` (or other name), which would disable horizontal scrolling, plus ensuring the week is displayed starting from monday.

@hoangnm  let me know if you prefer a different solution! The PR will be a draft for now.

### CODE REVIEW

**Comment by hoangnm** [comment]
Hi @pdpino, thanks again for your help! I think we can have the prop to prevent horizontal scrolling at the moment unless we have more use cases for the FixedWeekView.

**Comment by pdpino** [comment]
Ok, sounds good

I will refactor this PR soon!

**Comment by pdpino** [comment]
@hoangnm I updated the code and marked as ready:

* Added the prop `fixedHorizontally` 
* Deleted the extra `FixedWeekView` component
* I updated the README with an example of how to use the component as fixed
* I did move some functions to utils, to make the `WeekView` component smaller (should be easier to mantain)

**Review by AlissonEnz — APPROVED** [review]

**Comment by hoangnm** [comment]
Great, I'm merging now.

**Pull request merged**
