### PR TITLE
(hot)fix ANR: Add runOnJS prop

### LINKED ISSUE #259: BUG: GOOGLE PIXEL(Android 13)  hang on scrolling horizontal.
**Describe the bug**
On Android 13 in all google pixel devices. If I scroll the diary horizontally then after few seconds the app got hanging. if I move to other screens then came back to diary screen it works for few seconds and then hangs again.
    I face this hanging issue on  numberOfDays is set as 7 or 5. If 5 days is set then it hang after 10 seconds but id select it as 7 days then it hangs in 1 or 2 seconds.
   
**Visual demo**

https://user-images.githubusercontent.com/49557103/188266950-9a881341-ee3c-4d50-b2b4-7e72c6e78469.mov

**Steps To Reproduce**
  1. Open the calendar in Google Pixel 6,6a on android 13
  2. Scroll the calendar horizontally in 7 days view then you face the issue.

**Expected behaviour**
I expect it to scroll smother like other devices.

**Environment:**
 - `react-native-week-view`: 0.16.0
 - `react-native`: 0.66.4
 - `react`:17.0.2
 - OS: android 13 on Google Pixel devices

### PR DESCRIPTION
**Pull request by pdpino**
Hot fixes #259

### CODE REVIEW

**Comment by pdpino** [comment]
@hoangnm it fixes the issue in RNGH, as I reported in [this bug](https://github.com/software-mansion/react-native-gesture-handler/issues/2410) in their repo.

Setting `gesture.runOnJS(true)` makes the animations run in the JS context instead of the UI thread. In other words, the callback provided inside `onEnd(() => {...})` is run in the JS context instead of the UI thread. Apparently, the bug only occurs when running certain code on the UI thread.

In theory, animations are smoother when run in the UI thread. But still they can be run in JS and works fine. (Read more details in [rn-reanimated worklets docs](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/worklets/))

**Comment by hoangnm** [comment]
thanks, it makes sense, let's merge this to see if it works for other users.

**Review by hoangnm — APPROVED** [review]

**Comment by hoangnm** [comment]
wait, I can create the alpha version first.

**Comment by pdpino** [comment]
@hoangnm do you have an ETA on merging this? This issue has been waiting for long :sweat_smile:

**Comment by hoangnm** [comment]
ok, merging.

**Pull request merged**
